const Breeds = {
    Affenpinscher: "Affenpinscher",
    Afghan_Hound: "Afghan Hound",
    Africanis: "Africanis",
    Aidi: "Aidi",
    Airedale_Terrier: "Airedale Terrier",
    Akbash_Dog: "Akbash Dog",
    Akita_Inu: "Akita Inu",
    Alangu_Mastiff: "Alangu Mastiff",
    Alano_Español: "Alano Español",
    Alapaha_Blue_Blood_Bulldog: "Alapaha Blue Blood Bulldog",
    Alaskan_Klee_Kai: "Alaskan Klee Kai",
    Alaskan_Malamute: "Alaskan Malamute",
    Alaunt: "Alaunt",
    Alopekis: "Alopekis",
    Alpine_Dachsbracke: "Alpine Dachsbracke",
    Alsatian_Shepalute: "Alsatian Shepalute",
    American_Akita: "American Akita",
    American_Bulldog: "American Bulldog",
    American_Cocker_Spaniel: "American Cocker Spaniel",
    American_Eskimo_Dog: "American Eskimo Dog",
    American_Foxhound: "American Foxhound",
    American_Hairless_Terrier: "American Hairless Terrier",
    American_Mastiff: "American Mastiff",
    American_Pit_Bull_Terrier: "American Pit Bull Terrier",
    American_Staffordshire_Terrier: "American Staffordshire Terrier",
    American_Water_Spaniel: "American Water Spaniel",
    Anatolian_Shepherd_Dog: "Anatolian Shepherd Dog",
    Anglo_Français_de_Petite_Vénerie: "Anglo-Français de Petite Vénerie",
    Appenzeller_Sennenhund: "Appenzeller Sennenhund",
    Argentine_Dogo: "Argentine Dogo",
    Ariege_Pointer: "Ariege Pointer",
    Ariegeois: "Ariegeois",
    Armant: "Armant",
    Artois_Hound: "Artois Hound",
    Australian_Bulldog: "Australian Bulldog",
    Australian_Cattle_Dog: "Australian Cattle Dog",
    Australian_Kelpie: "Australian Kelpie",
    Australian_Shepherd: "Australian Shepherd",
    Australian_Silky_Terrier: "Australian Silky Terrier",
    Australian_Stumpy_Tail_Cattle_Dog: "Australian Stumpy Tail Cattle Dog",
    Australian_Terrier: "Australian Terrier",
    Austrian_Black_and_Tan_Hound: "Austrian Black and Tan Hound",
    Austrian_Pinscher: "Austrian Pinscher",
    Azawakh: "Azawakh",
    Bakharwal_Dog: "Bakharwal Dog",
    Barbet: "Barbet",
    Basenji: "Basenji",
    Basque_Shepherd_Dog: "Basque Shepherd Dog",
    Basset_Artésien_Normand: "Basset Artésien Normand",
    Basset_Bleu_de_Gascogne: "Basset Bleu de Gascogne",
    Basset_Fauve_de_Bretagne: "Basset Fauve de Bretagne",
    Grand_Basset_Griffon_Vendéen: "Grand Basset Griffon Vendéen",
    Petit_Basset_Griffon_Vendéen: "Petit Basset Griffon Vendéen",
    Bavarian_Mountain_Hound: "Bavarian Mountain Hound",
    Beagle: "Beagle",
    Beagle_Harrier: "Beagle-Harrier",
    Bearded_Collie: "Bearded Collie",
    Beauceron: "Beauceron",
    Bedlington_Terrier: "Bedlington Terrier",
    Belgian_Shepherd_Dog: "Belgian Shepherd Dog",
    Belgian_Shepherd_Dog_Groenendael: "Belgian Shepherd Dog (Groenendael)",
    Belgian_Shepherd_Dog_Laekenois: "Belgian Shepherd Dog (Laekenois)",
    Belgian_Shepherd_Dog_Malinois: "Belgian Shepherd Dog (Malinois)",
    Belgian_Shepherd_Tervuren: "Belgian Shepherd (Tervuren)",
    Bergamasco_Shepherd: "Bergamasco Shepherd",
    Berger_Blanc_Suisse: "Berger Blanc Suisse",
    Berger_Picard: "Berger Picard",
    Berner_Laufhund: "Berner Laufhund",
    Bernese_Mountain_Dog: "Bernese Mountain Dog",
    Bichon_Frisé: "Bichon Frisé",
    Billy: "Billy",
    Bisben: "Bisben",
    Black_and_Tan_Coonhound: "Black and Tan Coonhound",
    Black_and_Tan_Virginia_Foxhound: "Black and Tan Virginia Foxhound",
    Bullenbeisser: "Bullenbeisser",
    Black_Norwegian_Elkhound: "Black Norwegian Elkhound",
    Black_Russian_Terrier: "Black Russian Terrier",
    Blackmouth_Cur: "Blackmouth Cur",
    Grand_Bleu_de_Gascogne: "Grand Bleu de Gascogne",
    Petit_Bleu_de_Gascogne: "Petit Bleu de Gascogne",
    Bloodhound: "Bloodhound",
    Blue_Lacy: "Blue Lacy",
    Blue_Paul_Terrier: "Blue Paul Terrier",
    Bluetick_Coonhound: "Bluetick Coonhound",
    Boerboel: "Boerboel",
    Bohemian_Shepherd: "Bohemian Shepherd",
    Bolognese: "Bolognese",
    Border_Collie: "Border Collie",
    Border_Terrier: "Border Terrier",
    Borzoi: "Borzoi",
    Bosnian_Coarse_haired_Hound: "Bosnian Coarse-haired Hound",
    Boston_Terrier: "Boston Terrier",
    Bouvier_des_Ardennes: "Bouvier des Ardennes",
    Bouvier_des_Flandres: "Bouvier des Flandres",
    Boxer: "Boxer",
    Boykin_Spaniel: "Boykin Spaniel",
    Bracco_Italiano: "Bracco Italiano",
    Braque_dAuvergne: "Braque d'Auvergne",
    Braque_du_Bourbonnais: "Braque du Bourbonnais",
    Braque_du_Puy: "Braque du Puy",
    Braque_Francais: "Braque Francais",
    Braque_Saint_Germain: "Braque Saint-Germain",
    Brazilian_Terrier: "Brazilian Terrier",
    Briard: "Briard",
    Briquet_Griffon_Vendéen: "Briquet Griffon Vendéen",
    Brittany: "Brittany",
    Broholmer: "Broholmer",
    Bruno_Jura_Hound: "Bruno Jura Hound",
    Bucovina_Shepherd_Dog: "Bucovina Shepherd Dog",
    Bull_and_Terrier: "Bull and Terrier",
    Bull_Terrier: "Bull Terrier",
    Bull_Terrier_Miniature: "Bull Terrier (Miniature)",
    Bullmastiff: "Bullmastiff",
    Bully_Kutta: "Bully Kutta",
    Cairn_Terrier: "Cairn Terrier",
    Canaan_Dog: "Canaan Dog",
    Canadian_Eskimo_Dog: "Canadian Eskimo Dog",
    Canadian_Pointer: "Canadian Pointer",
    Cane_Corso: "Cane Corso",
    Cão_da_Serra_de_Aires: "Cão da Serra de Aires",
    Cão_de_Castro_Laboreiro: "Cão de Castro Laboreiro",
    Cão_Fila_de_São_Miguel: "Cão Fila de São Miguel",
    Carolina_Dog: "Carolina Dog",
    Carpathian_Shepherd_Dog: "Carpathian Shepherd Dog",
    Catahoula_Cur: "Catahoula Cur",
    Catalan_Sheepdog: "Catalan Sheepdog",
    Caucasian_Shepherd_Dog: "Caucasian Shepherd Dog",
    Cavalier_King_Charles_Spaniel: "Cavalier King Charles Spaniel",
    Central_Asian_Shepherd_Dog: "Central Asian Shepherd Dog",
    Cesky_Fousek: "Cesky Fousek",
    Cesky_Terrier: "Cesky Terrier",
    Polish_Greyhound: "Polish Greyhound",
    Chesapeake_Bay_Retriever: "Chesapeake Bay Retriever",
    Chien_gris: "Chien-gris",
    Chien_Français_Blanc_et_Noir: "Chien Français Blanc et Noir",
    Chien_Français_Blanc_et_Orange: "Chien Français Blanc et Orange",
    Chien_Français_Tricolore: "Chien Français Tricolore",
    Chihuahua: "Chihuahua",
    Chilean_Fox_Terrier: "Chilean Fox Terrier",
    Chinese_Chongqing_Dog: "Chinese Chongqing Dog",
    Chinese_Crested_Dog: "Chinese Crested Dog",
    Chinese_Imperial_Dog: "Chinese Imperial Dog",
    Chinook: "Chinook",
    Chippiparai: "Chippiparai",
    Chow_Chow: "Chow Chow",
    Cimarrón_Uruguayo: "Cimarrón Uruguayo",
    Cierny_Sery: "Cierny Sery",
    Cirneco_dellEtna: "Cirneco dell'Etna",
    Clumber_Spaniel: "Clumber Spaniel",
    Rough_Collie: "Rough Collie",
    Smooth_Collie: "Smooth Collie",
    Combai: "Combai",
    Cordoba_Fighting_Dog: "Cordoba Fighting Dog",
    Coton_de_Tulear: "Coton de Tulear",
    Cretan_Hound: "Cretan Hound",
    Croatian_Sheepdog: "Croatian Sheepdog",
    Cumberland_Sheepdog: "Cumberland Sheepdog",
    Curly_Coated_Retriever: "Curly Coated Retriever",
    Czechoslovakian_Wolfdog: "Czechoslovakian Wolfdog",
    Dachshund: "Dachshund",
    Dalmatian: "Dalmatian",
    Dandie_Dinmont_Terrier: "Dandie Dinmont Terrier",
    Danish_Swedish_Farmdog: "Danish Swedish Farmdog",
    Dingo: "Dingo",
    Doberman_Pinscher: "Doberman Pinscher",
    Dogue_de_Bordeaux: "Dogue de Bordeaux",
    Dogo_Cubano: "Dogo Cubano",
    Dogo_Guatemalteco: "Dogo Guatemalteco",
    Dogo_Sardesco: "Dogo Sardesco",
    Drentse_Patrijshond: "Drentse Patrijshond",
    Drever: "Drever",
    Dunker: "Dunker",
    Dutch_Shepherd_Dog: "Dutch Shepherd Dog",
    Dutch_Smoushond: "Dutch Smoushond",
    East_European_Shepherd: "East-European Shepherd",
    East_Siberian_Laika: "East Siberian Laika",
    Elo: "Elo",
    English_Cocker_Spaniel: "English Cocker Spaniel",
    English_Coonhound: "English Coonhound",
    English_Foxhound: "English Foxhound",
    English_Mastiff: "English Mastiff",
    English_Pointer: "English Pointer",
    English_Setter: "English Setter",
    English_Shepherd: "English Shepherd",
    English_Springer_Spaniel: "English Springer Spaniel",
    English_Toy_Terrier: "English Toy Terrier",
    English_Water_Spaniel: "English Water Spaniel",
    English_White_Terrier: "English White Terrier",
    Entlebucher_Mountain_Dog: "Entlebucher Mountain Dog",
    Épagneul_Bleu_de_Picardie: "Épagneul Bleu de Picardie",
    Estonian_Hound: "Estonian Hound",
    Estrela_Mountain_Dog: "Estrela Mountain Dog",
    Eurasier: "Eurasier",
    Field_Spaniel: "Field Spaniel",
    Fila_Brasileiro: "Fila Brasileiro",
    Findo: "Findo",
    Finnish_Hound: "Finnish Hound",
    Finnish_Lapphund: "Finnish Lapphund",
    Finnish_Spitz: "Finnish Spitz",
    Flat_Coated_Retriever: "Flat-Coated Retriever",
    Formosan_Mountain_Dog: "Formosan Mountain Dog",
    Fox_Terrier: "Fox Terrier",
    Wire_Fox_Terrier: "Wire Fox Terrier",
    French_Brittany: "French Brittany",
    French_Bulldog: "French Bulldog",
    French_Spaniel: "French Spaniel",
    Galgo_Español: "Galgo Español",
    German_Longhaired_Pointer: "German Longhaired Pointer",
    German_Pinscher: "German Pinscher",
    German_Shepherd_Dog: "German Shepherd Dog",
    German_Shorthaired_Pointer: "German Shorthaired Pointer",
    German_Spaniel: "German Spaniel",
    German_Spitz: "German Spitz",
    German_Wirehaired_Pointer: "German Wirehaired Pointer",
    Giant_Schnauzer: "Giant Schnauzer",
    Glen_of_Imaal_Terrier: "Glen of Imaal Terrier",
    Golden_Retriever: "Golden Retriever",
    Gordon_Setter: "Gordon Setter",
    Grand_Anglo_Français_Blanc_et_Noir: "Grand Anglo-Français Blanc et Noir",
    Grand_Anglo_Français_Blanc_et_Orange: "Grand Anglo-Français Blanc et Orange",
    Grand_Anglo_Français_Tricolore: "Grand Anglo-Français Tricolore",
    Grand_Griffon_Vendéen: "Grand Griffon Vendéen",
    Gran_Mastín_de_Borínquen: "Gran Mastín de Borínquen",
    Great_Dane: "Great Dane",
    Great_Pyrenees: "Great Pyrenees",
    Greater_Swiss_Mountain_Dog: "Greater Swiss Mountain Dog",
    Greenland_Dog: "Greenland Dog",
    Greyhound: "Greyhound",
    Griffon_Bleu_de_Gascogne: "Griffon Bleu de Gascogne",
    Griffon_Bruxellois: "Griffon Bruxellois",
    Griffon_Fauve_de_Bretagne: "Griffon Fauve de Bretagne",
    Griffon_Nivernais: "Griffon Nivernais",
    Gull_Dong: "Gull Dong",
    Gull_Terr: "Gull Terr",
    Hare_Indian_Dog: "Hare Indian Dog",
    Hamiltonstövare: "Hamiltonstövare",
    Hanover_Hound: "Hanover Hound",
    Harrier: "Harrier",
    Havanese: "Havanese",
    Hawaiian_Poi_Dog: "Hawaiian Poi Dog",
    Himalayan_Sheepdog: "Himalayan Sheepdog",
    Hokkaido: "Hokkaido",
    Hortaya_Borzaya: "Hortaya Borzaya",
    Hovawart: "Hovawart",
    Hungarian_Hound: "Hungarian Hound",
    New_Zealand_Huntaway: "New Zealand Huntaway",
    Hygenhund: "Hygenhund",
    Ibizan_Hound: "Ibizan Hound",
    Icelandic_Sheepdog: "Icelandic Sheepdog",
    Indian_Spitz: "Indian Spitz",
    Irish_Bull_Terrier: "Irish Bull Terrier",
    Irish_Red_and_White_Setter: "Irish Red and White Setter",
    Irish_Setter: "Irish Setter",
    Irish_Staffordshire_Bull_Terrier: "Irish Staffordshire Bull Terrier",
    Irish_Terrier: "Irish Terrier",
    Irish_Water_Spaniel: "Irish Water Spaniel",
    Irish_Wolfhound: "Irish Wolfhound",
    Istrian_Shorthaired_Hound: "Istrian Shorthaired Hound",
    Istrian_Coarse_haired_Hound: "Istrian Coarse-haired Hound",
    Italian_Greyhound: "Italian Greyhound",
    Jack_Russell_Terrier: "Jack Russell Terrier",
    Jagdterrier: "Jagdterrier",
    Jämthund: "Jämthund",
    Japanese_Chin: "Japanese Chin",
    Japanese_Spitz: "Japanese Spitz",
    Japanese_Terrier: "Japanese Terrier",
    Jonangi: "Jonangi",
    Kaikadi: "Kaikadi",
    Kai_Ken: "Kai Ken",
    Kangal_Dog: "Kangal Dog",
    Kanni: "Kanni",
    Karakachan_Dog: "Karakachan Dog",
    Karelian_Bear_Dog: "Karelian Bear Dog",
    Karst_Shepherd: "Karst Shepherd",
    Keeshond: "Keeshond",
    Kerry_Beagle: "Kerry Beagle",
    Kerry_Blue_Terrier: "Kerry Blue Terrier",
    King_Charles_Spaniel: "King Charles Spaniel",
    King_Shepherd: "King Shepherd",
    Kintamani: "Kintamani",
    Kishu: "Kishu",
    Komondor: "Komondor",
    Kooikerhondje: "Kooikerhondje",
    Koolie: "Koolie",
    Korean_Jindo_Dog: "Korean Jindo Dog",
    Korean_Mastiff: "Korean Mastiff",
    Kromfohrländer: "Kromfohrländer",
    Kunming_Wolf_dog: "Kunming Wolf-dog",
    Kuri: "Kuri",
    Kuvasz: "Kuvasz",
    Kyi_Leo: "Kyi-Leo",
    Labrador_Husky: "Labrador Husky",
    Labrador_Retriever: "Labrador Retriever",
    Lagotto_Romagnolo: "Lagotto Romagnolo",
    Lakeland_Terrier: "Lakeland Terrier",
    Lancashire_Heeler: "Lancashire Heeler",
    Landseer: "Landseer",
    Lapponian_Herder: "Lapponian Herder",
    Leonberger: "Leonberger",
    Lhasa_Apso: "Lhasa Apso",
    Lithuanian_Hound: "Lithuanian Hound",
    Longhaired_Whippet: "Longhaired Whippet",
    Lottatore_Brindisino: "Lottatore Brindisino",
    Löwchen: "Löwchen",
    Magyar_Agár: "Magyar Agár",
    Majestic_Tree_Hound: "Majestic Tree Hound",
    Maltese: "Maltese",
    Manchester_Terrier: "Manchester Terrier",
    Maremma_Sheepdog: "Maremma Sheepdog",
    McNab: "McNab",
    Mexican_Hairless_Dog: "Mexican Hairless Dog",
    Miniature_Australian_Shepherd: "Miniature Australian Shepherd",
    Miniature_Fox_Terrier: "Miniature Fox Terrier",
    Miniature_Pinscher: "Miniature Pinscher",
    Miniature_Schnauzer: "Miniature Schnauzer",
    Miniature_Siberian_Husky: "Miniature Siberian Husky",
    Mioritic: "Mioritic",
    Molossus: "Molossus",
    Montenegrin_Mountain_Hound: "Montenegrin Mountain Hound",
    Moscow_Watchdog: "Moscow Watchdog",
    Moscow_Water_Dog: "Moscow Water Dog",
    Mountain_Cur: "Mountain Cur",
    Mountain_View_Cur: "Mountain View Cur",
    Mucuchies: "Mucuchies",
    Mudi: "Mudi",
    Mudhol_Hound: "Mudhol Hound",
    Large_Münsterländer: "Large Münsterländer",
    Small_Münsterländer: "Small Münsterländer",
    Murray_River_Curly_Coated_Retriever: "Murray River Curly Coated Retriever",
    Neapolitan_Mastiff: "Neapolitan Mastiff",
    Newfoundland: "Newfoundland",
    New_Guinea_Singing_Dog: "New Guinea Singing Dog",
    Norfolk_Spaniel: "Norfolk Spaniel",
    Norfolk_Terrier: "Norfolk Terrier",
    Norrbottenspets: "Norrbottenspets",
    North_Country_Beagle: "North Country Beagle",
    Northern_Inuit_Dog: "Northern Inuit Dog",
    Norwegian_Buhund: "Norwegian Buhund",
    Norwegian_Elkhound: "Norwegian Elkhound",
    Norwegian_Lundehund: "Norwegian Lundehund",
    Norwich_Terrier: "Norwich Terrier",
    Nova_Scotia_Duck_Tolling_Retriever: "Nova Scotia Duck-Tolling Retriever",
    Old_Danish_Pointer: "Old Danish Pointer",
    Old_English_Sheepdog: "Old English Sheepdog",
    Old_English_Bulldog: "Old English Bulldog",
    Old_English_Terrier: "Old English Terrier",
    Old_German_Shepherd_Dog: "Old German Shepherd Dog",
    Olde_English_Bulldogge: "Olde English Bulldogge",
    Otterhound: "Otterhound",
    Pachon_Navarro: "Pachon Navarro",
    Paisley_Terrier: "Paisley Terrier",
    Papillon: "Papillon",
    Parson_Russell_Terrier: "Parson Russell Terrier",
    Patterdale_Terrier: "Patterdale Terrier",
    Pekingese: "Pekingese",
    Perro_de_Presa_Canario: "Perro de Presa Canario",
    Perro_de_Presa_Mallorquin: "Perro de Presa Mallorquin",
    Peruvian_Hairless_Dog: "Peruvian Hairless Dog",
    Phalène: "Phalène",
    Pharaoh_Hound: "Pharaoh Hound",
    Picardy_Spaniel: "Picardy Spaniel",
    Plott_Hound: "Plott Hound",
    Podenco_Canario: "Podenco Canario",
    Pointer: "Pointer",
    Polish_Hound: "Polish Hound",
    Polish_Hunting_Dog: "Polish Hunting Dog",
    Polish_Lowland_Sheepdog: "Polish Lowland Sheepdog",
    Polish_Tatra_Sheepdog: "Polish Tatra Sheepdog",
    Pomeranian: "Pomeranian",
    Pont_Audemer_Spaniel: "Pont-Audemer Spaniel",
    Poodle: "Poodle",
    Porcelaine: "Porcelaine",
    Portuguese_Podengo: "Portuguese Podengo",
    Portuguese_Pointer: "Portuguese Pointer",
    Portuguese_Water_Dog: "Portuguese Water Dog",
    Pražský_Krysarík: "Pražský Krysarík",
    Pudelpointer: "Pudelpointer",
    Pug: "Pug",
    Puli: "Puli",
    Pumi: "Pumi",
    Pungsan_Dog: "Pungsan Dog",
    Pyrenean_Mastiff: "Pyrenean Mastiff",
    Pyrenean_Shepherd: "Pyrenean Shepherd",
    Rafeiro_do_Alentejo: "Rafeiro do Alentejo",
    Rajapalayam: "Rajapalayam",
    Rampur_Greyhound: "Rampur Greyhound",
    Rastreador_Brasileiro: "Rastreador Brasileiro",
    Ratonero_Bodeguero_Andaluz: "Ratonero Bodeguero Andaluz",
    Rat_Terrier: "Rat Terrier",
    Redbone_Coonhound: "Redbone Coonhound",
    Rhodesian_Ridgeback: "Rhodesian Ridgeback",
    Rottweiler: "Rottweiler",
    Russian_Spaniel: "Russian Spaniel",
    Russkiy_Toy: "Russkiy Toy",
    Russo_European_Laika: "Russo-European Laika",
    Russell_Terrier: "Russell Terrier",
    Saarlooswolfhond: "Saarlooswolfhond",
    Sabueso_Español: "Sabueso Español",
    Sage_Ashayeri: "Sage Ashayeri",
    Sage_Mazandarani: "Sage Mazandarani",
    Sakhalin_Husky: "Sakhalin Husky",
    Saluki: "Saluki",
    Samoyed: "Samoyed",
    Sapsali: "Sapsali",
    Šarplaninac: "Šarplaninac",
    Schapendoes: "Schapendoes",
    Schillerstövare: "Schillerstövare",
    Schipperke: "Schipperke",
    Old_Croatian_Sighthound: "Old Croatian Sighthound",
    Standard_Schnauzer: "Standard Schnauzer",
    Schweizer_Laufhund: "Schweizer Laufhund",
    Schweizerischer_Niederlaufhund: "Schweizerischer Niederlaufhund",
    Scotch_Collie: "Scotch Collie",
    Scottish_Deerhound: "Scottish Deerhound",
    Scottish_Terrier: "Scottish Terrier",
    Sealyham_Terrier: "Sealyham Terrier",
    Segugio_Italiano: "Segugio Italiano",
    Seppala_Siberian_Sleddog: "Seppala Siberian Sleddog",
    Serbian_Hound: "Serbian Hound",
    Serbian_Tricolour_Hound: "Serbian Tricolour Hound",
    Shar_Pei: "Shar Pei",
    Shetland_Sheepdog: "Shetland Sheepdog",
    Shiba_Inu: "Shiba Inu",
    Shih_Tzu: "Shih Tzu",
    Shikoku: "Shikoku",
    Shiloh_Shepherd_Dog: "Shiloh Shepherd Dog",
    Shirak: "Shirak",
    Siberian_Husky: "Siberian Husky",
    Silken_Windhound: "Silken Windhound",
    Sinhala_Hound: "Sinhala Hound",
    Skye_Terrier: "Skye Terrier",
    Sloughi: "Sloughi",
    Slovak_Cuvac: "Slovak Cuvac",
    Slovakian_Rough_haired_Pointer: "Slovakian Rough-haired Pointer",
    Slovenský_Kopov: "Slovenský Kopov",
    Smålandsstövare: "Smålandsstövare",
    Small_Greek_Domestic_Dog: "Small Greek Domestic Dog",
    Soft_Coated_Wheaten_Terrier: "Soft-Coated Wheaten Terrier",
    South_Russian_Ovcharka: "South Russian Ovcharka",
    Southern_Hound: "Southern Hound",
    Spanish_Mastiff: "Spanish Mastiff",
    Spanish_Water_Dog: "Spanish Water Dog",
    Spinone_Italiano: "Spinone Italiano",
    Sporting_Lucas_Terrier: "Sporting Lucas Terrier",
    St_Bernard: "St. Bernard",
    St_Johns_Water_Dog: "St. John's Water Dog",
    Stabyhoun: "Stabyhoun",
    Staffordshire_Bull_Terrier: "Staffordshire Bull Terrier",
    Stephens_Cur: "Stephens Cur",
    Styrian_Coarse_haired_Hound: "Styrian Coarse-haired Hound",
    Sussex_Spaniel: "Sussex Spaniel",
    Swedish_Lapphund: "Swedish Lapphund",
    Swedish_Vallhund: "Swedish Vallhund",
    Swedish_Beagle: "Swedish Beagle",
    Tahltan_Bear_Dog: "Tahltan Bear Dog",
    Taigan: "Taigan",
    Tamaskan_Dog: "Tamaskan Dog",
    Teddy_Roosevelt_Terrier: "Teddy Roosevelt Terrier",
    Telomian: "Telomian",
    Tenterfield_Terrier: "Tenterfield Terrier",
    Thai_Bangkaew_Dog: "Thai Bangkaew Dog",
    Thai_Ridgeback: "Thai Ridgeback",
    Tibetan_Mastiff: "Tibetan Mastiff",
    Tibetan_Spaniel: "Tibetan Spaniel",
    Tibetan_Terrier: "Tibetan Terrier",
    Tornjak: "Tornjak",
    Tosa: "Tosa",
    Toy_Bulldog: "Toy Bulldog",
    Toy_Fox_Terrier: "Toy Fox Terrier",
    Toy_Manchester_Terrier: "Toy Manchester Terrier",
    Treeing_Cur: "Treeing Cur",
    Treeing_Walker_Coonhound: "Treeing Walker Coonhound",
    Tyrolean_Hound: "Tyrolean Hound",
    Utonagan: "Utonagan",
    Vizsla: "Vizsla",
    Volpino_Italiano: "Volpino Italiano",
    Weimaraner: "Weimaraner",
    Cardigan_Welsh_Corgi: "Cardigan Welsh Corgi",
    Pembroke_Welsh_Corgi: "Pembroke Welsh Corgi",
    Welsh_Sheepdog: "Welsh Sheepdog",
    Welsh_Springer_Spaniel: "Welsh Springer Spaniel",
    Welsh_Terrier: "Welsh Terrier",
    West_Highland_White_Terrier: "West Highland White Terrier",
    West_Siberian_Laika: "West Siberian Laika",
    Westphalian_Dachsbracke: "Westphalian Dachsbracke",
    Wetterhoun: "Wetterhoun",
    Whippet: "Whippet",
    White_English_Bulldog: "White English Bulldog",
    White_Shepherd_Dog: "White Shepherd Dog",
    Wirehaired_Vizsla: "Wirehaired Vizsla",
    Wirehaired_Pointing_Griffon: "Wirehaired Pointing Griffon",
    Yorkshire_Terrier: "Yorkshire Terrier",
}

export default Breeds;